/**
 * Discovered Services Writer
 * Generates YAML file showing auto-discovered services
 */

import fs from 'fs';
import { stringify as stringifyYaml } from 'yaml';
import logger from '../utils/logger.js';

export default class DiscoveredServicesWriter {
  constructor(outputPath = './discovered-services.yml') {
    this.outputPath = outputPath;
  }

  /**
   * Write discovered services to YAML file
   * @param {Object} discovered - Discovered services from ServiceDiscovery
   */
  write(discovered) {
    try {
      const yamlContent = this.generateYaml(discovered);
      fs.writeFileSync(this.outputPath, yamlContent, 'utf8');

      logger.info('Updated discovered services file', {
        path: this.outputPath,
        services: discovered.summary.totalServices,
      });
    } catch (error) {
      logger.error('Failed to write discovered services', {
        error: error.message,
        path: this.outputPath,
      });
    }
  }

  /**
   * Generate YAML content with helpful header comments
   * @param {Object} discovered - Discovered services
   * @returns {string} - YAML content
   */
  generateYaml(discovered) {
    const header = `# Auto-generated by Watchdog
# Last scan: ${discovered.timestamp}
# Scan duration: ${discovered.scanDuration}ms
# Total services: ${discovered.summary.totalServices}
#
# This file shows what Watchdog discovered on your system.
# To customize monitoring, create 'watchdog.config.yml'
# See watchdog.config.example.yml for options.
#
`;

    const data = {
      discovered: {
        docker: discovered.docker.map((c) => ({
          name: c.name,
          ports: c.ports,
          hasHealthCheck: c.hasHealthCheck,
          image: c.image,
        })),
        pm2: discovered.pm2.map((p) => ({
          name: p.name,
          status: p.status,
          port: p.port,
          restarts: p.restarts,
        })),
        systemd: discovered.systemd.map((s) => s.name),
      },
    };

    return header + stringifyYaml(data);
  }

  /**
   * Read existing discovered services file
   * @returns {Object|null} - Previously discovered services or null
   */
  read() {
    try {
      if (!fs.existsSync(this.outputPath)) {
        return null;
      }

      const content = fs.readFileSync(this.outputPath, 'utf8');
      return content;
    } catch (error) {
      logger.error('Failed to read discovered services', {
        error: error.message,
      });
      return null;
    }
  }

  /**
   * Check if discovered services file exists
   * @returns {boolean} - True if file exists
   */
  exists() {
    return fs.existsSync(this.outputPath);
  }
}
